### ISSUE TITLE
Path for Background Image on Layout does update when switching between computers.

### ISSUE THREAD

**Issue by DewaltGuy** [smeighan/xLights#1316]
The background image for layout preview doesn't correct itself when switching between different computers.  I have tried storing the background image in my show directory and media directory (within my show directory).  

My show directory is located on my user profile path (C:\Users\<changes for each device>\Holiday Lights\2018\Christmas\)
When I move to a different device the path for the image is still pointing to the previous devices location which is a different profile path as the user account is different.

This would appear to be a bug as images, etc within sequences are automatically corrected when they are within the show directory.

**Comment by keithsw1111** [comment]
I need to see the log file ... because it should be working and the log will let us see why it didnt work.

**Comment by DewaltGuy** [comment]
I added the log file.
It shows me changing the path and image back
2018-11-07 09:35:47,956 17784 log_base [DEBUG] Loading background image file C:\Users\e1524\iCloudDrive\Holiday Light Shows\Light Shows\2018\Christmas\Media\HousePictureCropped.jpg

But it doesn't seem to show to the incorrect path.  Here is what the path said 
before I changed it for the other computer I am working on.
C:\Users\trevo\iCloudDrive\Holiday Light Shows\Light Shows\2018\Christmas\Media\HousePictureCropped.jpg

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/2558064/xLightsProblem.zip)

**Comment by AzGilrock** [comment]
If you like to keep images in subdirectories below the show directory I find xLights doesn't fix them.  I just imported effects for TheGreatestShowman and I had to manually fix all the paths to the photos because I had everything in a subdirectory of the show folder.  Same is probably true for the background photo since you have it in a media subfolder.

**Comment by keithsw1111** [comment]
If you take someone elses sequence and you want paths to be automagically corrected you must:

1. Place the sequence in a subfolder of your show directory.
2. Change to the imported show folder, open the sequence ... AND SAVE IT (rgbeffects and sequence) ... this crystalises the corrected paths in the files.
3. Change back to your show folder and do the import ... all paths should now be correct ... even if you copy show folder to another machine in a different path as long as the show folder name does not change.

**Comment by AzGilrock** [comment]
Yeah I don't like the way it works.  If I started over I would change it but I would not be allowing users to have media anywhere they want it.  I would just hard-code it so every sequence gets a subfolder that contains all it's associated media and it would make copying someone's sequence so much smoother.

**Comment by AJ240-Aus** [comment]
Keith, is it possible to have all paths relative to the show folder instead of the primary path?
That way if you copy a show folder from one computer to another, the sub folders within the show folder are relative. I.e. Show folder c:\users\UserName\XlightsShow\ then all subsequent paths are relative to this \Media \Music etc So an image would be referenced as \Media\image.gif instead of c:\Users\UserName\XlightsShow\Media\Image.gif . Just a thought, as I have issues moving things between PC's even when using identical paths on both machines. Videos in particular need to be re selected every time I move from one PC to another. Really annoying. 
![relative paths](https://user-images.githubusercontent.com/44983381/48374293-8e740680-e718-11e8-98b5-aca18fc896a6.jpg)

**Comment by keithsw1111** [comment]
Relative paths sound nice but they are a pain to implement ... and as long as your files are in a show folder whos name doesnt change ... ie the last folder in the show folder path (not the whole path) then xLights will automagically correct it as it loads. If you believe this is not working then I need log evidence as hundreds of users use this every day without issue ... including myself.

The only time it wont auto correct is if the file still exists in the absolute path on the machine ... in which case there is no need to update it.

The only logs I have above show the files being correctly loaded.

Last chance guys ... I either get logs that prove there is an issue or i close this one.

**Comment by AJ240-Aus** [comment]
Keith, the problem I have seen is that the path appears to be correct, but I need to re-select the video file to get it to render, otherwise the video shows as red. I will try and reproduce it with a small sequence and get you some logs. What files do you want ?

**Comment by AJ240-Aus** [comment]
I have tried several times and cannot reproduce it. Not sure what happened in the past.
