### ISSUE TITLE
xlights version 2019.60 Crashing when editing submodel. 

### ISSUE THREAD

**Issue by Zuseleets** [smeighan/xLights#1775]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

When editing a submodel, xlights crashes on saving my changes.
  
**To Reproduce**
1. Click on the submodels within the model 
2. Select the submodel name
3. Click on draw model 
4. Click ok
5. Click ok to get out of sub models window
6. Click save in layout tab
7. Xlights crashes

 

**Versions (please complete the following information):**
 Windows 10
xlights version 2019.60

**Additional context**
usually crashes without debug report window. Although the last time it happened, it did, which I will include here.

[xLights_dbgrpt-8204-20191023T235317.zip](https://github.com/smeighan/xLights/files/3762795/xLights_dbgrpt-8204-20191023T235317.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3762804/xLightsProblem.zip)

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
It is crashing in UnSelectAllModels ... I wonder if the submodel was selected and when we update it the submodel pointer becomes invalid ... which is then used in the unselect.

Can you be more precise about how you get into the submodel dialog. How do you select the model (using the list or the layout image). Do you select the model in the list or the submodel in the list.

Then I assume you select the submodel elipses to get into the submodel dialog.

**Comment by Zuseleets** [comment]
Morning! 

I select the model from the layout image, and then select the Sub-Models ellipsis to edit. 

Cheers, 

Suz

**Comment by keithsw1111** [comment]
I assume this is now fixed.

**Comment by Zuseleets** [comment]
No it’s not fixed. It crashed while I was making a submodel two nights ago. Xlights created a debut report. I can send it through? I just thought it was useless if I can’t duplicate it when it happens. 

Suz

**Comment by keithsw1111** [comment]
Odd I have been looking at crash reports and there are almost none occurring outside of the usual background volume of OpenGL crashes I largely attribute to driver issues.
