### ISSUE TITLE
Easylights Controller Removed?

### ISSUE THREAD

**Issue by pstechsolutions** [smeighan/xLights#1840]
In version 64 I had setup an Easylights Pix 16 v3 controller and now in 65-67 I no longer see it as an available choice.  Also until I went back to 64 and removed the controller from my setup, I was unable to use the newer versions since they would crash anytime I tried to access the controller settings. Same experience using both the windows version and the linux appimage.  

Thank you all for everything you've put into this project.

**Comment by computergeek1507** [comment]
In my experience if you right click on the output it would crash. I fixed that crash. Double clicking on the output worked for me, so I am unsure how you are accessing the controlling settings that doesn't work.

**Comment by pstechsolutions** [comment]
Double Click indeed does function as expected (thank you for pointing that out).  However I am still getting the crash if I Right Click.
