### ISSUE TITLE
xlights 2020.55-x86_64.AppImage seg fault

### ISSUE THREAD

**Issue by andyb2000** [smeighan/xLights#2410]
**Describe the bug**
Running the appimage binary results in seg fault immediately after the xlights splash/logo page.
Tried with -d debug on and off, same issue (in debug I get the dialogue showing debug is on first)
I'm currently running ./xLights-2020.23-x86_64.AppImage without issue.

**To Reproduce**

Environment - Ubuntu 20.04.1 LTS
xLights-2020.55-x86_64.AppImage
(in folder where previous version also exists)

**Expected behavior**
Run without segfault

**Screenshots**

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - xLights version: 2020.55-x86_64

Output ran under strace:
<snip non-relevant>
`[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 53) = 53
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "17", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x3864d9", 8)    = 8
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f7869fa84d9", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 65) = 65
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "18", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "wxArtProvider::GetBitmap(wxStrin"..., 85) = 85
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x4d8", 5)       = 5
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f786a0289c8", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 65) = 65
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "19", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "xLightsFrame::xLightsFrame(wxWin"..., 42) = 42
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0xc168", 6)      = 6
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b3340148", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "20", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "xLightsApp::OnInit()", 20) = 20
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x17fa", 6)      = 6
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b32da91a", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "21", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "wxEntry(int&amp;, wchar_t**)", 28) = 28
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x92", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f786941a172", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 60) = 60
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "22", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "main", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0xc3", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b2f41513", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "23", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "__libc_start_main", 17) = 17
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0xf3", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f7868b470b3", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/lib/x86_64-linux-gnu/libc.so.6", 31) = 31
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "24", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "_start", 6)      = 6
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x2a", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b2f7f57a", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n  ", 3)        = 3
[pid 46398] write(10, "</", 2)          = 2
[pid 46398] write(10, "stack", 5)       = 5
[pid 46398] write(10, ">", 1)           = 1
[pid 46398] write(10, "\n", 1)          = 1
[pid 46398] write(10, "</", 2)          = 2
[pid 46398] write(10, "report", 6)      = 6
[pid 46398] write(10, ">", 1)           = 1
[pid 46398] write(10, "\n", 1)          = 1
[pid 46398] ioctl(10, TCGETS, 0x7ffc43b67b70) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 46398] fstat(10, {st_mode=S_IFREG|0644, st_size=69965, ...}) = 0
[pid 46398] fsync(10)                   = 0
[pid 46398] close(10)                   = 0
[pid 46398] stat("/tmp/xLights_dbgrpt-46398-20201214T130446/xLights.xml", {st_mode=S_IFREG|0644, st_size=69965, ...}) = 0
[pid 46398] lstat("xlights_networks.xml", {st_mode=S_IFREG|0664, st_size=2261, ...}) = 0
[pid 46398] stat("/tmp/xLights_dbgrpt-46398-20201214T130446/xlights_networks.xml", 0x7ffc43b67ed0) = -1 ENOENT (No such file or directory)
[pid 46398] lstat("xlights_rgbeffects.xml", {st_mode=S_IFREG|0664, st_size=12175, ...}) = 0
[pid 46398] stat("/tmp/xLights_dbgrpt-46398-20201214T130446/xlights_rgbeffects.xml", 0x7ffc43b67ed0) = -1 ENOENT (No such file or directory)
[pid 46398] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1301} ---
[pid 46448] <... futex resumed>)        = ?
[pid 46413] <... clock_nanosleep resumed> <unfinished ...>) = ?
[pid 46412] <... futex resumed>)        = ?
[pid 46447] <... poll resumed>)         = -1 ENOENT (No such file or directory)
[pid 46448] +++ killed by SIGSEGV (core dumped) +++
[pid 46447] +++ killed by SIGSEGV (core dumped) +++
[pid 46413] +++ killed by SIGSEGV (core dumped) +++
[pid 46412] +++ killed by SIGSEGV (core dumped) +++
[pid 46402] <... write resumed>)        = -1 EPIPE (Broken pipe)
[pid 46401] <... read resumed>"@\0\0\0\35\0\0\0\362\21\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64
[pid 46402] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=46401, si_uid=0} ---
[pid 46401] writev(5, [{iov_base="\20\0\0\0\0\0\0\0\362\21\0\0\0\0\0\0", iov_len=16}], 1 <unfinished ...>
[pid 46402] kill(46401, SIGTERM <unfinished ...>
[pid 46401] <... writev resumed>)       = 16
[pid 46402] <... kill resumed>)         = 0
[pid 46401] --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=46401, si_uid=0} ---
[pid 46402] madvise(0x7f9580d63000, 8368128, MADV_DONTNEED <unfinished ...>
[pid 46401] rt_sigreturn({mask=[]} <unfinished ...>
[pid 46402] <... madvise resumed>)      = 0
[pid 46401] <... rt_sigreturn resumed>) = 16
[pid 46402] exit(0 <unfinished ...>
[pid 46401] munmap(0x7f95817e1000, 139264 <unfinished ...>
[pid 46402] <... exit resumed>)         = ?
[pid 46401] <... munmap resumed>)       = 0
[pid 46402] +++ exited with 0 +++
[pid 46401] rt_sigaction(SIGHUP, NULL, {sa_handler=0x7f958157db50, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
[pid 46401] rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
[pid 46401] rt_sigaction(SIGINT, NULL, {sa_handler=0x7f958157db50, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
[pid 46401] rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
[pid 46398] +++ killed by SIGSEGV (core dumped) +++
rt_sigaction(SIGTERM, NULL, {sa_handler=0x7f958157db50, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
poll([{fd=5, events=0}], 1, 0)          = 0 (Timeout)
close(5)                                = 0
geteuid()                               = 0
lstat("/etc/mtab", {st_mode=S_IFLNK|0777, st_size=19, ...}) = 0
umount2("/tmp/.mount_xLightThlyRz", MNT_DETACH) = 0
rmdir("/tmp/.mount_xLightThlyRz")       = 0
munmap(0x7f9581564000, 254240)          = 0
exit_group(0)                           = ?
+++ exited with 0 +++
Segmentation fault
`

**Comment by andyb2000** [comment]
Eww, sorry code formatting looks terrible.
Try again:

`
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 53) = 53
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "17", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x3864d9", 8)    = 8
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f7869fa84d9", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 65) = 65
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "18", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "wxArtProvider::GetBitmap(wxStrin"..., 85) = 85
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x4d8", 5)       = 5
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f786a0289c8", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 65) = 65
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "19", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "xLightsFrame::xLightsFrame(wxWin"..., 42) = 42
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0xc168", 6)      = 6
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b3340148", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "20", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "xLightsApp::OnInit()", 20) = 20
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x17fa", 6)      = 6
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b32da91a", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "21", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "wxEntry(int&amp;, wchar_t**)", 28) = 28
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x92", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f786941a172", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/usr/bin"..., 60) = 60
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "22", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "main", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0xc3", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b2f41513", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "23", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "__libc_start_main", 17) = 17
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0xf3", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x7f7868b470b3", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/lib/x86_64-linux-gnu/libc.so.6", 31) = 31
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n    ", 5)      = 5
[pid 46398] write(10, "<", 1)           = 1
[pid 46398] write(10, "frame", 5)       = 5
[pid 46398] write(10, " level=\"", 8)   = 8
[pid 46398] write(10, "24", 2)          = 2
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " function=\"", 11) = 11
[pid 46398] write(10, "_start", 6)      = 6
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " offset=\"", 9)  = 9
[pid 46398] write(10, "0x2a", 4)        = 4
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " address=\"", 10) = 10
[pid 46398] write(10, "0x5601b2f7f57a", 14) = 14
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, " module=\"", 9)  = 9
[pid 46398] write(10, "/tmp/.mount_xLightThlyRz/AppRun."..., 39) = 39
[pid 46398] write(10, "\"", 1)          = 1
[pid 46398] write(10, "/>", 2)          = 2
[pid 46398] write(10, "\n  ", 3)        = 3
[pid 46398] write(10, "</", 2)          = 2
[pid 46398] write(10, "stack", 5)       = 5
[pid 46398] write(10, ">", 1)           = 1
[pid 46398] write(10, "\n", 1)          = 1
[pid 46398] write(10, "</", 2)          = 2
[pid 46398] write(10, "report", 6)      = 6
[pid 46398] write(10, ">", 1)           = 1
[pid 46398] write(10, "\n", 1)          = 1
[pid 46398] ioctl(10, TCGETS, 0x7ffc43b67b70) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 46398] fstat(10, {st_mode=S_IFREG|0644, st_size=69965, ...}) = 0
[pid 46398] fsync(10)                   = 0
[pid 46398] close(10)                   = 0
[pid 46398] stat("/tmp/xLights_dbgrpt-46398-20201214T130446/xLights.xml", {st_mode=S_IFREG|0644, st_size=69965, ...}) = 0
[pid 46398] lstat("xlights_networks.xml", {st_mode=S_IFREG|0664, st_size=2261, ...}) = 0
[pid 46398] stat("/tmp/xLights_dbgrpt-46398-20201214T130446/xlights_networks.xml", 0x7ffc43b67ed0) = -1 ENOENT (No such file or directory)
[pid 46398] lstat("xlights_rgbeffects.xml", {st_mode=S_IFREG|0664, st_size=12175, ...}) = 0
[pid 46398] stat("/tmp/xLights_dbgrpt-46398-20201214T130446/xlights_rgbeffects.xml", 0x7ffc43b67ed0) = -1 ENOENT (No such file or directory)
[pid 46398] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1301} ---
[pid 46448] <... futex resumed>)        = ?
[pid 46413] <... clock_nanosleep resumed> <unfinished ...>) = ?
[pid 46412] <... futex resumed>)        = ?
[pid 46447] <... poll resumed>)         = -1 ENOENT (No such file or directory)
[pid 46448] +++ killed by SIGSEGV (core dumped) +++
[pid 46447] +++ killed by SIGSEGV (core dumped) +++
[pid 46413] +++ killed by SIGSEGV (core dumped) +++
[pid 46412] +++ killed by SIGSEGV (core dumped) +++
[pid 46402] <... write resumed>)        = -1 EPIPE (Broken pipe)
[pid 46401] <... read resumed>"@\0\0\0\35\0\0\0\362\21\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64
[pid 46402] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=46401, si_uid=0} ---
[pid 46401] writev(5, [{iov_base="\20\0\0\0\0\0\0\0\362\21\0\0\0\0\0\0", iov_len=16}], 1 <unfinished ...>
[pid 46402] kill(46401, SIGTERM <unfinished ...>
[pid 46401] <... writev resumed>)       = 16
[pid 46402] <... kill resumed>)         = 0
[pid 46401] --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=46401, si_uid=0} ---
[pid 46402] madvise(0x7f9580d63000, 8368128, MADV_DONTNEED <unfinished ...>
[pid 46401] rt_sigreturn({mask=[]} <unfinished ...>
[pid 46402] <... madvise resumed>)      = 0
[pid 46401] <... rt_sigreturn resumed>) = 16
[pid 46402] exit(0 <unfinished ...>
[pid 46401] munmap(0x7f95817e1000, 139264 <unfinished ...>
[pid 46402] <... exit resumed>)         = ?
[pid 46401] <... munmap resumed>)       = 0
[pid 46402] +++ exited with 0 +++
[pid 46401] rt_sigaction(SIGHUP, NULL, {sa_handler=0x7f958157db50, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
[pid 46401] rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
[pid 46401] rt_sigaction(SIGINT, NULL, {sa_handler=0x7f958157db50, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
[pid 46401] rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
[pid 46398] +++ killed by SIGSEGV (core dumped) +++
rt_sigaction(SIGTERM, NULL, {sa_handler=0x7f958157db50, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f95817c83c0}, NULL, 8) = 0
poll([{fd=5, events=0}], 1, 0)          = 0 (Timeout)
close(5)                                = 0
geteuid()                               = 0
lstat("/etc/mtab", {st_mode=S_IFLNK|0777, st_size=19, ...}) = 0
umount2("/tmp/.mount_xLightThlyRz", MNT_DETACH) = 0
rmdir("/tmp/.mount_xLightThlyRz")       = 0
munmap(0x7f9581564000, 254240)          = 0
exit_group(0)                           = ?
+++ exited with 0 +++
Segmentation fault

`

**Comment by codephotog** [comment]
Environment - Ubuntu 20.10 in a Unraid VM.
xLights-2020.55-x86_64.AppImage

I don't know if it is the same issue: 
./xLights-2020.55-x86_64.AppImage 
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 09:36:35.035: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:36:35.045: Failed to load module "canberra-gtk-module"
sh: 1: addr2line: not found
Segmentation fault (core dumped)

**Comment by fone626** [comment]
I'm having the same issue with 2020.55
I briefly see the crash window open and then closes on it's own with nothing started at all.
I'm running Kubuntu 20.04.1

**Comment by cjd** [comment]
I reproduced this on my system as well.
A manual compile works fine.
Debug logs show it crashes in libpng so there is something odd in libpng within the appimage build
Looking into it now

**Comment by whvneo** [comment]
Hi, 

I'm getting the same error even with the downloaded AppImage and self compiled.

My strace at the end looks like thi:
`
write(36, "/>", 2)                      = 2
write(36, "\n  ", 3)                    = 3
write(36, "</", 2)                      = 2
write(36, "stack", 5)                   = 5
write(36, ">", 1)                       = 1
write(36, "\n", 1)                      = 1
write(36, "</", 2)                      = 2
write(36, "report", 6)                  = 6
write(36, ">", 1)                       = 1
write(36, "\n", 1)                      = 1
ioctl(36, TCGETS, 0x7fffe98d2430)       = -1 ENOTTY (Unpassender IOCTL (I/O-Control) für das Gerät)
fstat(36, {st_mode=S_IFREG|0664, st_size=4128, ...}) = 0
fsync(36)                               = 0
close(36)                               = 0
stat("/tmp/xLights_dbgrpt-8721-20201218T173349/xLights.xml", {st_mode=S_IFREG|0664, st_size=4128, ...}) = 0
lstat("xlights_networks.xml", 0x7fffe98d2a70) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
lstat("xlights_rgbeffects.xml", 0x7fffe98d2a70) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1309} ---

`

**Comment by cjd** [comment]
I've changed the build a bit (based off debian buster instead of ubuntu bionic) which changes up some of the libraries (libpng in particular)
Can folks give a try of https://www.adebenham.com/wp-content/uploads/xlights/xLights-2020.56-x86_64.AppImage and let me know if it works for them?

**Comment by fone626** [comment]
> Can folks give a try of https://www.adebenham.com/wp-content/uploads/xlights/xLights-2020.56-x86_64.AppImage and let me know if it works for them?

It looks like your hard work has paid off, and it's no longer crashing for me... THANKS!

**Comment by cjd** [comment]
Excellent - then it should be fixed in the next auto-build release as well :)

**Comment by ashleysommer** [comment]
I don't know if its related, but I'm using xLights-2020.56-x86_64.AppImage from the Github Releases page: https://github.com/smeighan/xLights/releases/tag/2020.56 and still getting a segfault.

```
 ./xLights-2020.56-x86_64.AppImage
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 11:59:09.128: Failed to load module "colorreload-gtk-module"
Gtk-Message: 11:59:09.128: Failed to load module "window-decorations-gtk-module"
[1]    15568 segmentation fault (core dumped)  ./xLights-2020.56-x86_64.AppImage
```

BT in GDB:
```
Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:144
144     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:144
#1  0x00007fffe78596f5 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libpng16.so.16
#2  0x00007fffe7849d2b in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libpng16.so.16
#3  0x00007fffe784a1c4 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libpng16.so.16
#4  0x00007fffe784a3c5 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libpng16.so.16
#5  0x00007fffe784a55b in png_process_data () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libpng16.so.16
#6  0x00007fff845f4d5a in  () at /tmp/.mount_xLightN1hrMJ//usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
#7  0x00007fffe7ed7281 in  () at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#8  0x00007fffe7ed7b15 in gdk_pixbuf_loader_close () at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#9  0x00007fffe7ed4233 in  () at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#10 0x00007fffe7ed52c1 in gdk_pixbuf_new_from_stream () at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#11 0x00007fffe7ed544a in gdk_pixbuf_new_from_resource () at /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
#12 0x00007fffe844bfd8 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#13 0x00007fffe844f368 in gtk_icon_info_load_icon () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#14 0x00007fffe844f5b4 in gtk_icon_theme_load_icon_for_scale () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#15 0x00007fffe84488a3 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#16 0x00007fffe8448fb7 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#17 0x00007fffe84490e4 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#18 0x00007fffe84492c8 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#19 0x00007fffe845c5cd in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#20 0x00007fffe83c1393 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#21 0x00007fffe83c54a1 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#22 0x00007fffe845cd23 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#23 0x00007fffe8523651 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#24 0x00007fffe85238ec in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#25 0x00007fffe8523bf5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#26 0x00007fffe8371b86 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#27 0x00007fffe83c1393 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#28 0x00007fffe83c54a1 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#29 0x00007fffe83724e3 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#30 0x00007fffe8523651 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#31 0x00007fffe85238ec in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#32 0x00007fffe8523bf5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#33 0x00007fffe83c1393 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#34 0x00007fffe83c54a1 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#35 0x00007fffe837ef23 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#36 0x00007fffe8523651 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#37 0x00007fffe85238ec in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#38 0x00007fffe8523bf5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#39 0x00007fffe8523d33 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#40 0x00007fffe85a5642 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#41 0x00007fffe85230dc in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#42 0x00007fffe85238ec in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#43 0x00007fffe8523bf5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#44 0x00007fffe8523d33 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#45 0x00007fffe85ac11a in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#46 0x00007fffe85ac646 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#47 0x00007fffe85b2625 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#48 0x00007fffe7f7e080 in  () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgdk-3.so.0
#49 0x00007fffebad4e8e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007fffebad5240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#51 0x00007fffebad5533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#52 0x00007fffe8481a25 in gtk_main () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libgtk-3.so.0
#53 0x00007ffff3b6a875 in wxGUIEventLoop::DoRun() () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libwx_gtk3u_core-3.1.so.5
#54 0x00007ffff2fec213 in wxEventLoopBase::Run() () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libwx_baseu-3.1.so.5
#55 0x00007ffff3bd8ad8 in wxDialog::ShowModal() () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libwx_gtk3u_core-3.1.so.5
#56 0x000055555673f5f4 in xLightsFrame::PromptForShowDirectory(bool) ()
#57 0x000055555605da84 in xLightsFrame::xLightsFrame(wxWindow*, int) ()
#58 0x0000555555fe881a in xLightsApp::OnInit() ()
#59 0x00007ffff303e172 in wxEntry(int&, wchar_t**) () at /tmp/.mount_xLightN1hrMJ/usr/bin/../lib/libwx_baseu-3.1.so.5
#60 0x0000555555c4e7a3 in main ()
```

**Comment by ashleysommer** [comment]
Update: I tried the xLights-2020.56-x86_64.AppImage file linked above from the adebenham.com site and it works fine, so there is definitely a difference between that one, and the xLights-2020.56-x86_64.AppImage on the releases page.

**Comment by cjd** [comment]
Yes, the fix I made was after the 2020.56 release was made - so it won't show up in the autobuilds until the next release
