### ISSUE TITLE
PPD Sequence crashing with shaders on a mini tree

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3240]
From Zoom .. Thanh Mai was working on this .. we narrowed it down to one group that caused it to crash. If we remove the shaders, it renders. If we import from this sequence to our own layouts, it seems to work. Attached is the crash dump and the sequence with JUST the one group in it. 
Unzip, change to this layout, load the sequence and render, it crashed.

[xLights_dbgrpt-8100-20220514T175200.zip](https://github.com/smeighan/xLights/files/8693961/xLights_dbgrpt-8100-20220514T175200.zip)
[Marshmello_-_Shockwave bug test.zip](https://github.com/smeighan/xLights/files/8693962/Marshmello_-_Shockwave.bug.test.zip)
.

**Comment by keithsw1111** [comment]
Does it crash with the daily build ... i suspect this is already fixed.

**Comment by derwin12** [comment]
We hadn't tried yet. I am away now but mark is likely still in zoom.

**Comment by MDickson00** [comment]
I tried the latest nightly build and I also noticed 2022.10 is out and tried it as well, it still crashes.

**Comment by derwin12** [comment]
If I remove just tree8 it works .. hmm... let me see if I can find what makes 8 so special.

**Comment by tmai02** [comment]
i tried create a new mini tree and replace a model 8, and import effect still crashes

**Comment by keithsw1111** [comment]
I have cut the sequence down ... to a much smaller version that still crashes  but out of time tonight. This looks like some sort of corruption so typically tricky to find.
[ttt.zip](https://github.com/smeighan/xLights/files/8694709/ttt.zip)

**Comment by tmai02** [comment]
This is fresh make layout for my friend demo, everything in the layout was copy from PPD Pro layout once and duplicate, everything else work but the mini trees.

**Comment by dkulp** [comment]
I see what the problem is, trying to figure out a solution now....
